### ISSUE TITLE
There is only one related script in the directory “Scripts”

### ISSUE THREAD

**Issue by bismarck1008** [andreaminio/AnnotationPipeline-EVM_based-DClab#1]
for example，there is no “GFF_extract_features.py” script

**Comment by andreaminio** [comment]
Good morning @bismarck1008

You were right, _GFF_extract_features.py_ script was missing. Thanks for noticing. Now you can find it in the script folder.

-A

**Comment by bismarck1008** [comment]
Thank you very much for your prompt reply，but the script need "GFF_lib" , I have not foound it.

**Comment by andreaminio** [comment]
Hi @bismarck1008 

I've updated the file with a version not making use of the external function library.

**Comment by bismarck1008** [comment]
Thank you. I have a try

**Comment by bismarck1008** [comment]
missing doFilter_bam.read_coverage_identity.py

**Comment by andreaminio** [comment]
Hi @bismarck1008 

I went back to check all python scripts that were missing.

Before closing the ticket, can I know our name please so I can properly thank you?

**Comment by bismarck1008** [comment]
You are so polite,my name is Mark.

**Comment by andreaminio** [comment]
Hi Mark, Thanks for reaching out. I hope you'll find the pipeline useful for your research.
