### ISSUE TITLE
SNAP prediction erro

### ISSUE THREAD

**Issue by unavailable-2374** [andreaminio/AnnotationPipeline-EVM_based-DClab#5]
zff2gff3.pl prediction.snap.txt | gffread -E --force-exons -O -F -o - .....

Segmentation fault (core dumped)

prediction.snap.txt:
"""
>M1_hap1_chr01
Einit   3257    3373    -       -6.432  0       0       2       M1_hap1_chr01-snap.1
Exon    2739    3026    -       8.987   0       0       1       M1_hap1_chr01-snap.1
Exon    2311    2619    -       5.596   0       0       0       M1_hap1_chr01-snap.1
Eterm   722     799     -       -6.641  0       0       2       M1_hap1_chr01-snap.1
Einit   8970    9222    -       25.445  0       1       0       M1_hap1_chr01-snap.2
Exon    7446    7455    -       13.580  2       2       2       M1_hap1_chr01-snap.2
Eterm   7201    7297    -       15.205  1       0       0       M1_hap1_chr01-snap.2
Einit   14092   14147   -       2.203   0       2       1       M1_hap1_chr01-snap.3
Exon    13713   13997   -       -30.601 1       2       2       M1_hap1_chr01-snap.3
Exon    13197   13310   -       3.035   1       2       2       M1_hap1_chr01-snap.3
Exon    12888   13095   -       1.833   1       0       1       M1_hap1_chr01-snap.3
Eterm   9238    9261    -       6.719   0       0       0       M1_hap1_chr01-snap.3
Einit   14214   14744   +       -14.381 0       0       2       M1_hap1_chr01-snap.4
Exon    15083   15470   +       -3.806  0       1       1       M1_hap1_chr01-snap.4
Eterm   15654   15817   +       9.817   2       0       1       M1_hap1_chr01-snap.4
Esngl   15872   16885   +       21.195  0       0       1       M1_hap1_chr01-snap.5
Einit   16892   17065   +       0.466   0       0       1       M1_hap1_chr01-snap.6
Exon    20490   20596   +       18.166  0       2       2       M1_hap1_chr01-snap.6
Exon    20697   20840   +       6.386   1       2       0       M1_hap1_chr01-snap.6
Eterm   22763   22811   +       18.577  1       0       2       M1_hap1_chr01-snap.6
"""

after i try to run the zff2gff3.pl 

"""
##gff-version 3
#region M1_hap1_chr01
M1_hap1_chr01   snap    CDS     3257    3373    .       -       Name=M1_hap1_chr01-snap.1
M1_hap1_chr01   snap    CDS     2739    3026    .       -       Name=M1_hap1_chr01-snap.1
M1_hap1_chr01   snap    CDS     2311    2619    .       -       Name=M1_hap1_chr01-snap.1
M1_hap1_chr01   snap    CDS     722     799     .       -       Name=M1_hap1_chr01-snap.1
M1_hap1_chr01   snap    CDS     8970    9222    .       -       Name=M1_hap1_chr01-snap.2
M1_hap1_chr01   snap    CDS     7446    7455    .       -       Name=M1_hap1_chr01-snap.2
M1_hap1_chr01   snap    CDS     7201    7297    .       -       Name=M1_hap1_chr01-snap.2
M1_hap1_chr01   snap    CDS     14092   14147   .       -       Name=M1_hap1_chr01-snap.3
M1_hap1_chr01   snap    CDS     13713   13997   .       -       Name=M1_hap1_chr01-snap.3
M1_hap1_chr01   snap    CDS     13197   13310   .       -       Name=M1_hap1_chr01-snap.3
M1_hap1_chr01   snap    CDS     12888   13095   .       -       Name=M1_hap1_chr01-snap.3
M1_hap1_chr01   snap    CDS     9238    9261    .       -       Name=M1_hap1_chr01-snap.3
M1_hap1_chr01   snap    CDS     14214   14744   .       +       Name=M1_hap1_chr01-snap.4
M1_hap1_chr01   snap    CDS     15083   15470   .       +       Name=M1_hap1_chr01-snap.4
M1_hap1_chr01   snap    CDS     15654   15817   .       +       Name=M1_hap1_chr01-snap.4
M1_hap1_chr01   snap    CDS     15872   16885   .       +       Name=M1_hap1_chr01-snap.5
M1_hap1_chr01   snap    CDS     16892   17065   .       +       Name=M1_hap1_chr01-snap.6
M1_hap1_chr01   snap    CDS     20490   20596   .       +       Name=M1_hap1_chr01-snap.6
M1_hap1_chr01   snap    CDS     20697   20840   .       +       Name=M1_hap1_chr01-snap.6
M1_hap1_chr01   snap    CDS     22763   22811   .       +       Name=M1_hap1_chr01-snap.6
"""

and then I use it to run the gffread ,erro happend

Could  you help me to solve it , thanks!

zhou

**Comment by andreaminio** [comment]
Hi Zhou,

I never had runtime errors with _gffread_, it may be that zff2gff3.pl is producing some weird result. I cannot be sure 100% as the tabbing of the output file is gone, but a correct gff3 should have 9 columns and it seems your output is missing the phase column for some reaso. This may be the origin of the issue, however I'm not sure if in such a case gffread would throw a core dump or a different kind of error.

Andrea

**Comment by unavailable-2374** [comment]
Hi Andrea

thank you for your reply!!!

It has confused me for too long,but as you see the zff2gff3.pl just print out 8 columns :

![image](https://user-images.githubusercontent.com/92284733/171076271-2902f4b7-b0bd-41b8-b2a5-79afa631a961.png)

could you share your zff2gff3.pl to me , or tell me how to fix this script , truly thanks!

zhou

**Comment by zhouyflab** [comment]
I try to fix the script by add a columns like this

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/103104171/171076935-dbec5afc-e0c8-475f-ac88-5e8b766da885.png">

but it still not work 

the cmd told me 

"""
gffread -E --force-exons -O -F -o -
   .. loaded 0 genomic features from stdin
"""

I am so curious, and my project really need your pipeline to annotation genome , could you help me 

my sincerely thanks !

zhou

**Comment by andreaminio** [comment]
Hi Yongfeng,

I see my _zff2gff3.pl_ script is probably older and different exactly in that line. I added a copy of it in the [script folder](Scripts/zff2gff3.pl).

Now, to _gffread_ issue, it seems that the file stream in input is reaching the script but is not able to parse it correctly and read any feature form it. From what I see, however, the structure of the input is the one of a correct GFF3, so it looks pretty weird. It may be a hidden issue, did you check the new line symbols (unix ones, not windows) and the separators (only tabs, no multiple spaces)? These issues may be difficult to spot, and in the picture or text online I cannot verify it.

Andrea

**Comment by zhouyflab** [comment]
Thank you very much! I will forward this to my student.


Cheers,
Yongfeng




--

Prof. Yongfeng Zhou
Professor of Horticulture at AGIS, CAAS
Population Genomics and Genomic Breeding of Grapevine
Cell/Wechat: 13924607807, twitter: @yongfeng_zhou
Email: ***@***.******@***.***
The Agricultural Genomics Institute at Shenzhen, The Chinese Academy of Agricultural Sciences



From: Andrea Minio ***@***.***>
Date: 2022-05-31 23:49:59
To: andreaminio/AnnotationPipeline-EVM_based-DClab ***@***.***>
Cc: zhouyflab ***@***.***>,Comment ***@***.***>
Subject: Re: [andreaminio/AnnotationPipeline-EVM_based-DClab] SNAP prediction erro (Issue #5)

Hi Yongfeng,
I see my zff2gff3.pl script is probably older and different exactly in that line. I added a copy of it in the script folder.
Now, to gffread issue, it seems that the file stream in input is reaching the script but is not able to parse it correctly and read any feature form it. From what I see, however, the structure of the input is the one of a correct GFF3, so it looks pretty weird. It may be a hidden issue, did you check the new line symbols (unix ones, not windows) and the separators (only tabs, no multiple spaces)? These issues may be difficult to spot, and in the picture or text online I cannot verify it.
Andrea
