### ISSUE TITLE
Question about merging Stringtie, Trinity(on genome), Trinity(de novo) results

### ISSUE THREAD

**Issue by yaoxkkkkk** [andreaminio/AnnotationPipeline-EVM_based-DClab#6]
Thank you for your innovation on this annotation pipeline. I am carrying out [0.2.2 - RNAseq assembly](https://github.com/andreaminio/AnnotationPipeline-EVM_based-DClab/blob/master/Pipeline/022_RNAseq_assembly.md#022---rnaseq-assembly) part of this pipeline. I have finished the three methods and I got some gff3 files, I wonder that what I can do to merge the three part results and move forward to the final step [0.2.2.4 - Export useful files](https://github.com/andreaminio/AnnotationPipeline-EVM_based-DClab/blob/master/Pipeline/022_RNAseq_assembly.md#0224---export-useful-files)?

**Comment by yaoxkkkkk** [comment]
More question:
```
cat ${name}.trinity.og.on.genome.cov_iden_g95.fasta.transdecoder.gff3 | awk '$7!="-"' > ${name}.trinity.og.on.genome.cov_iden_g95.fasta.transdecoder.no_minus.gff3
```
Why the genes located on minus strand need to be eliminated?

**Comment by andreaminio** [comment]
Hi Yao,

1. You can move to 0.2.2.4 as long as you finish all the necessary/possible assembly procedures. The code in that section should work no matter how many assemblies you did, and should be fine afterwards.
2.  Transdecoder is not run on genes, but on transcripts sequences in that phase. As the "negative" strand of the mRNA transcript is not translated, we remove the call as potential noise.

**Comment by yaoxkkkkk** [comment]
Glad to receive your instant reply! I am tring to follow process this section to the final part, but I still met a minor bug about GFF_extract_features.py. I have created a new environment which python version is Python 2.7.18 :: Anaconda, Inc.. Here is the error message:
```
$ python GFF_extract_features.py 
Traceback (most recent call last):
  File "GFF_extract_features.py", line 7, in <module>
    import pandas as pd
  File "/dssg/home/acct-jiang.lu/jiang.lu/anaconda3/envs/py2/lib/python2.7/site-packages/pandas/__init__.py", line 13, in <module>
    __import__(dependency)
  File "/dssg/home/acct-jiang.lu/jiang.lu/anaconda3/envs/py2/lib/python2.7/site-packages/dateutil/__init__.py", line 5, in <module>
    from ._version import version as __version__
  File "/dssg/home/acct-jiang.lu/jiang.lu/anaconda3/envs/py2/lib/python2.7/site-packages/dateutil/_version.py", line 10
    version: str
           ^
SyntaxError: invalid syntax
```

**Comment by yaoxkkkkk** [comment]
I still confuse about [0.2.2 - RNAseq assembly](https://github.com/andreaminio/AnnotationPipeline-EVM_based-DClab/blob/master/Pipeline/022_RNAseq_assembly.md#022---rnaseq-assembly). Although there are three methods listed here, I only need to complete any of them, instead of completing them all, am I understanding correctly?😂

**Comment by yaoxkkkkk** [comment]
Oh I figure it out, it's due to the way of installing the package. I installed the pandas using pip, then here is the error message. Then I use anaconda to install pandas, the problem solved!
